### ISSUE TITLE
请问下载Paratranz这一步是怎么做的

### ISSUE THREAD

**Issue by H4M5TER** [linonetwo/CDDA-Kenan-Modpack-Chinese#10]
想给翻译项目也整一套自动化。
看不太懂这一段 ```fetch(zipUrl, { method: 'GET', headers: { Authorization: process.env.PARATRANZ_TOKEN } })```。
我浏览器监听下载没有发现 headers 里有 Authorization 字段，这似乎是 fetch 标准里的东西。
请问这里的 Authorization 字段是怎么工作的，如果我想直接使用 wget 应该怎么写。
以及这里的 PARATRANZ_TOKEN 是 Paratranz 的 Cookie 里的哪部分。

**Comment by linonetwo** [comment]
你好，获取token的方式，我问了他们开发者，是这样的：

> 点右上角的头像，进去有个小钥匙的图标，可以获取API TOKEN，用这个请求。

还有 Authorization 是 REST API 里很常用的一个字段，放在 request header 里的。

**Comment by linonetwo** [comment]
好像因为这个仓库是 fork 的，所以没有收到 issue 的提醒…

**Comment by H4M5TER** [comment]
谢谢你！
