### ISSUE TITLE
0.G   "MMA_Mods_Extension" 应该用不了了

### ISSUE THREAD

**Issue by linonetwo** [linonetwo/CDDA-Kenan-Modpack-Chinese#30]
DEBUG    : Weapon cbma_mono_spear in style 漠风 doesn't exist.

 FUNCTION : check_martialarts
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\martialarts.cpp
 LINE     : 507
 VERSION  : d6ec466
 DEBUG    : Weapon nec_fine_katana in style 钢魂 doesn't exist.

 FUNCTION : check_martialarts
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\martialarts.cpp
 LINE     : 507
 VERSION  : d6ec466
 DEBUG    : Weapon bio_lightsaber_fake in style 钢魂 doesn't exist.

 FUNCTION : check_martialarts
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\martialarts.cpp
 LINE     : 507
 VERSION  : d6ec466
 DEBUG    : Weapon ninja_katana in style 钢魂 doesn't exist.

 FUNCTION : check_martialarts
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\martialarts.cpp
 LINE     : 507
 VERSION  : d6ec466
 DEBUG    : Weapon hf_blade in style 钢魂 doesn't exist.

 FUNCTION : check_martialarts
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\martialarts.cpp
 LINE     : 507
 VERSION  : d6ec466
 DEBUG    : Weapon laser_sword_on_vo in style 海拉尔剑术 doesn't exist.

 FUNCTION : check_martialarts
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\martialarts.cpp
 LINE     : 507
 VERSION  : d6ec466
 DEBUG    : Weapon cbma_mono_sword in style 海拉尔剑术 doesn't exist.

 FUNCTION : check_martialarts
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\martialarts.cpp
 LINE     : 507
 VERSION  : d6ec466
 DEBUG    : Weapon nec_fine_katana in style 海拉尔剑术 doesn't exist.

 FUNCTION : check_martialarts
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\martialarts.cpp
 LINE     : 507
 VERSION  : d6ec466

**Comment by waveyl** [comment]
这个是因为武术的兼容列表要把所有能够兼容的武器全部写上去，如果mod没开全就会出现这个报错，忽略掉就好了

**Comment by linonetwo** [comment]
除了MMA还要开啥MOD吗

**Comment by waveyl** [comment]
Mod介绍有写，但是很多mod都已经不维护了，所以没必要纠结这个
![Screenshot_20230914_225424.png](https://github.com/linonetwo/CDDA-Kenan-Modpack-Chinese/assets/22638873/6d476d0e-a203-4e4b-a540-2e1f6d61929a)

**Comment by linonetwo** [comment]
的确是这样……
