### ISSUE TITLE
为什么最新的发行版中，空岛模组（CDDA-Sky-islands）没有了？

### ISSUE THREAD

**Issue by RuikangSun** [linonetwo/CDDA-Kenan-Modpack-Chinese#31]
以前根据这个[帖子](https://tieba.baidu.com/p/8312283084)了解到Kenan整合包包括空岛模组，但最近我下载较新版本发现已经没有这个模组了。
排查的时候发现，帖子[提到的版本](https://github.com/linonetwo/CDDA-Kenan-Modpack-Chinese/releases/tag/2023-03-11-1737)是有CDDA-Sky-islands空岛模组的，但[较新的版本](https://github.com/linonetwo/CDDA-Kenan-Modpack-Chinese/releases/tag/2023-11-15-1156)文件内已经找不到空岛模组了。
请问中文模组维护者们是否了解，是出于什么原因Kenan整合包不在提供空岛模组了吗？谢谢！

**Comment by RuikangSun** [comment]
顺便一提，本github repo主页[连接到的网址](https://onetwo.ren/CDDA-Kenan-Modpack-Chinese/#Index:Index%20README.md)，里面提到了一个QQ群，原本想加群问一下的，但入群验证似乎有点难

**Comment by waveyl** [comment]
因为自带了

**Comment by RuikangSun** [comment]
> 因为自带了

是测试版自带的嘛？0.G似乎还没有，我去看看。感谢分享！
